preload = /home/fwaith/Pictures/Wallpapers/Nyansky_M Miku Top.png
preload = /home/fwaith/Pictures/Wallpapers/Nyansky_M Miku Bottom.png

wallpaper = eDP-1, /home/fwaith/Pictures/Wallpapers/Nyansky_M Miku Top.png
wallpaper = DP-1, /home/fwaith/Pictures/Wallpapers/Nyansky_M Miku Bottom.png
