# ┌─────────────────────────┐
# │       WORKSPACES        │
# └─────────────────────────┘

# Create persistent workspaces
workspace = 1, persistent:true
workspace = 2, persistent:true
workspace = 3, persistent:true
workspace = 4, persistent:true
workspace = 5, persistent:true
workspace = 6, persistent:true

# Change workspace
bind = $mainMod, code:14, workspace, 1  # (
bind = $mainMod, code:17, workspace, 2  # )
bind = $mainMod, code:13, workspace, 3  # }
bind = $mainMod, code:18, workspace, 4  # +
bind = $mainMod, code:12, workspace, 5  # {
bind = $mainMod, code:19, workspace, 6  # ]

binds {
  allow_workspace_cycles = true
}

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6

bind = $mainMod, S, togglespecialworkspace, magic
bind = $mainMod SHIFT, S, movetoworkspace, special:magic

bind = $mainMod, mouse_down, workspace, e+1
bind = $mainMod, mouse_up, workspace, e-1

bind = $mainMod, Right, workspace, e+1
bind = $mainMod, Left, workspace, e-1
